spring:
  application:
    name: lms-iuonly-impl
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
  datasource:
    postgres:
      driverClassName: ${lms.db.driverClass}
      jdbcUrl: ${lms.db.url}
      username: ${lms.db.user}
      password: ${lms.db.password}
      type: org.springframework.jdbc.datasource.DriverManagerDataSource
    denodo:
      driverClassName: ${denodo.db.driverClass}
      jdbcUrl: ${denodo.db.url}
      username: ${denodo.db.user}
      password: ${denodo.db.password}
derdack:
  baseUrl: ${derdack.rest.baseUrl}
  apiKey: ${derdack.rest.apiKey}
  team: ${derdack.rest.team}
  recipientEmail: dsobiera@iu.edu
  env: ${app.env}
